### ISSUE TITLE
DemoPermissionsAndroid.dproj Doesn't compile unde Delphi 11

### ISSUE THREAD

**Issue by Poopsie69** [DeveloppeurPascal/Delphi-samples#8]
**Describe the bug**

[DCC Error] uAccueil.pas(54): E2250 There is no overloaded version of 'RequestPermissions' that can be called with these arguments

**To Reproduce**
Click "Run" on the tool bar

**Expected behavior**
compiled binary

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Delphi 11.3

**Comment by DeveloppeurPascal** [comment]
Thanks for your message. The problem has been fixed.
